export const LOGIN_SESSION = 'LOGIN_SESSION';
export const LOGOUT_SESSION = 'LOGOUT_SESSION';
export const SET_USER = 'SET_USER';
export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';

